name: build

# on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Parse Ref
        id: parse-ref
        run: |
          echo ::set-output name=name::${GITHUB_REF#refs/*/}
          echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
          # echo ::set-output name=version::${GITHUB_REF#refs/tags/version-}

      - name: Git checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: lein deps

      - name: Run test
        run: lein test
